### PR TITLE
solving #19 issue

### PR DESCRIPTION
**Pull request by abhinav-TB**

### CODE REVIEW

**Review by rncampos — CHANGES_REQUESTED** [review]
Dear Abhinav. Thanks for your interest in py_heideltime. We have just been informed that py_heideltime was no longer working with the last version of emoji package (2.0). Your efforts in correcting this are mostly appreciated. However I noticed two things that I will kindly ask you to correct before we can proceed. 

First, your pull request is including a change on readme pointing towards your github. 

Second there are some issues with your code. The first is that you suggested to include in line 1 the code "from genericpath import isdir" yet isdir is never used in the code. Further to this, you suggest to remove shutil.rmtree(directory_name), yet this code is needed, as for bigger files of text, py_heideltime creates some temp files that need to be deleted afterward.

Can you please fix these issues so that we can accept your pull request?

Thanks
Ric

**Comment by abhinav-TB** [comment]
HI @rncampos thanks for the heads up, I came up with a solution in which the final block was remove and a isdir check is preformed before deletion , what's your thought on this ?

**Review by rncampos — APPROVED** [review]
Its perfect now. Thanks

**Comment by rncampos** [comment]
Fixed the error created upon the release of the emojis package version.

**Pull request merged**
